language: node_js
node_js:
  - "stable"
before_script:
  - npm install -g bower
  - bower install
script:
  - npm run rules && npm run test
after_success:
  - bash ./.tools/deploy-gh-pages.sh
env:
  - VERSION=draft-00