language: node_js
node_js:
  - "stable"
before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
before_script:
  - npm install -g bower
  - bower install
script:
  - npm run rules
after_success:
  - bash ./.tools/deploy-gh-pages.sh
env:
  - VERSION=draft-00
